"""
Admin helpers for hardening the built-in (Spider) MySQL databases.

    python -m app.hardening_tools export-allowlist
        Reads the router index (ChromaDB "spiderman_databases") and writes the
        names to data/builtin_databases.txt. Commit that file: it makes the
        allow-list explicit, reviewable and independent of Chroma.

    python -m app.hardening_tools mysql-grants [--user qc_readonly] [--host %]
        Prints SQL that creates a SELECT-only MySQL account limited to exactly
        the allow-listed databases. Review it, replace CHANGE_ME, run it as a
        MySQL administrator, then set MYSQL_RO_USER / MYSQL_RO_PASSWORD.

    python -m app.hardening_tools check [--connect]
        Prints the current MySQL security findings (what the server logs at
        start-up). With --connect it also connects and audits the REAL grants
        of the account the application uses (SHOW GRANTS), because having
        MYSQL_RO_USER set proves nothing about what that account may do.

    python -m app.hardening_tools scan-secrets [--root PATH]
        Scans the working tree for hard-coded credentials and API keys. Values
        are never printed. Exit code 1 when anything is found. Scanning the
        working tree does NOT inspect git history; see docs/SECURITY.md.
"""

from __future__ import annotations

import argparse
import sys

from app import db_registry, mysql_hardening, secret_scan
from app.secrets_redaction import install_log_redaction

install_log_redaction()


def _names_for_grants() -> frozenset[str]:
    """Allow-list from env/file; falls back to the router index."""

    names = db_registry.builtin_databases()

    if names:
        return names

    # Importing queryclarify registers the router-index provider. It is a heavy
    # import (embedding model), so only do it when nothing else is configured.
    from app import queryclarify  # noqa: F401

    db_registry.invalidate_builtin_cache()

    return db_registry.builtin_databases()


def cmd_export_allowlist(args: argparse.Namespace) -> int:
    from app import queryclarify

    names = sorted(
        db_registry.clean_builtin_names(
            queryclarify._builtin_names_from_router_index()
        )
    )

    if not names:
        print(
            "The router index returned no databases; nothing was written.",
            file=sys.stderr,
        )
        return 1

    path = (
        db_registry.Path(args.output)
        if args.output
        else db_registry.builtin_allowlist_file()
    )
    path.parent.mkdir(parents=True, exist_ok=True)

    header = (
        "# Built-in databases QueryClarify may query (one per line).\n"
        "# Generated by: python -m app.hardening_tools export-allowlist\n"
        "# System schemas (mysql, information_schema, performance_schema, sys)\n"
        "# are always rejected, even if listed here.\n"
    )
    path.write_text(header + "\n".join(names) + "\n", encoding="utf-8")

    print(f"Wrote {len(names)} databases to {path}")
    return 0


def cmd_mysql_grants(args: argparse.Namespace) -> int:
    names = _names_for_grants()

    if not names:
        print(
            "The allow-list is empty. Run `export-allowlist` first or set "
            "QC_BUILTIN_DATABASES.",
            file=sys.stderr,
        )
        return 1

    try:
        sql = mysql_hardening.build_grant_sql(
            names, user=args.user, host=args.host
        )
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    print(sql, end="")
    return 0


def cmd_check(args: argparse.Namespace) -> int:
    findings = mysql_hardening.security_warnings()

    if args.connect:
        _names_for_grants()  # registers the router-index provider if needed
        findings += [
            f"MySQL account: {finding}"
            for finding in mysql_hardening.privilege_findings()
        ]

    if not findings:
        print("No MySQL security findings.")
        return 0

    for finding in findings:
        print("WARNING:", finding)

    return 1


def cmd_scan_secrets(args: argparse.Namespace) -> int:
    findings = secret_scan.scan_repository(args.root)

    if not findings:
        print("No hard-coded credentials found in the working tree.")
        print("(Git history is not inspected: run `git log --all -S<value>`.)")
        return 0

    for finding in findings:
        print(finding.render())

    print(f"\n{len(findings)} finding(s). Remove them and ROTATE any real secret.")
    return 1


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="python -m app.hardening_tools")
    sub = parser.add_subparsers(dest="command", required=True)

    export = sub.add_parser("export-allowlist", help=cmd_export_allowlist.__doc__)
    export.add_argument("--output", help="file to write (default: data/builtin_databases.txt)")
    export.set_defaults(func=cmd_export_allowlist)

    grants = sub.add_parser("mysql-grants", help="print SELECT-only account SQL")
    grants.add_argument("--user", default="qc_readonly")
    grants.add_argument("--host", default="%")
    grants.set_defaults(func=cmd_mysql_grants)

    check = sub.add_parser("check", help="print current security findings")
    check.add_argument(
        "--connect", action="store_true",
        help="also connect and audit the account's real grants",
    )
    check.set_defaults(func=cmd_check)

    scan = sub.add_parser("scan-secrets", help="scan the working tree for credentials")
    scan.add_argument("--root", default=str(secret_scan.PROJECT_ROOT))
    scan.set_defaults(func=cmd_scan_secrets)

    args = parser.parse_args(argv)

    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
